# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from pydantic import BaseModel, PrivateAttr


class getDomains(BaseModel):
    """
    Returns supported domains.
    """

    __domain__: str = PrivateAttr("Schema")
