# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.domains.deviceaccess.types import *


class deviceRequestPrompted(BaseModel):
    """
        A device request opened a user prompt to select a device. Respond with the
    selectPrompt or cancelPrompt command.
    """

    __domain__: str = PrivateAttr("DeviceAccess")
    id: "RequestId"
    devices: list
