# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import TypeVar

from pydantic import BaseModel

RequestId = TypeVar("RequestId", bound=str)
"""
Device request id.
"""

DeviceId = TypeVar("DeviceId", bound=str)
"""
A device id.
"""


class PromptDevice(BaseModel):
    """
    Device information displayed in a user prompt to select a device.
    """

    id: "DeviceId"
    name: str
    """
    Display name as it appears in a device request user prompt.
    """
