# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from pydantic import BaseModel, PrivateAttr


class clearMessages(BaseModel):
    """
    Does nothing.
    """

    __domain__: str = PrivateAttr("Console")


class disable(BaseModel):
    """
    Disables console domain, prevents further console messages from being reported to the client.
    """

    __domain__: str = PrivateAttr("Console")


class enable(BaseModel):
    """
        Enables console domain, sends the messages collected so far to the client by means of the
    `messageAdded` notification.
    """

    __domain__: str = PrivateAttr("Console")
