# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.domains.autofill.types import *


class addressFormFilled(BaseModel):
    """
    Emitted when an address form is filled.
    """

    __domain__: str = PrivateAttr("Autofill")
    filledFields: list
    """
    Information about the fields that were filled
    """
    addressUi: "AddressUI"
    """
    An UI representation of the address used to fill the form.
Consists of a 2D array where each child represents an address/profile line.
    """
