# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from enum import Enum

from pydantic import BaseModel

from cidipi.domains import dom, page


class CreditCard(BaseModel):
    number: str
    """
    16-digit credit card number.
    """
    name: str
    """
    Name of the credit card owner.
    """
    expiryMonth: str
    """
    2-digit expiry month.
    """
    expiryYear: str
    """
    4-digit expiry year.
    """
    cvc: str
    """
    3-digit card verification code.
    """


class AddressField(BaseModel):
    name: str
    """
    address field name, for example GIVEN_NAME.
    """
    value: str
    """
    address field value, for example Jon Doe.
    """


class AddressFields(BaseModel):
    """
    A list of address fields.
    """

    fields: list


class Address(BaseModel):
    fields: list
    """
    fields and values defining an address.
    """


class AddressUI(BaseModel):
    """
        Defines how an address can be displayed like in chrome://settings/addresses.
    Address UI is a two dimensional array, each inner array is an "address information line", and when rendered in a UI surface should be displayed as such.
    The following address UI for instance:
    [[{name: "GIVE_NAME", value: "Jon"}, {name: "FAMILY_NAME", value: "Doe"}], [{name: "CITY", value: "Munich"}, {name: "ZIP", value: "81456"}]]
    should allow the receiver to render:
    Jon Doe
    Munich 81456
    """

    addressFields: list
    """
    A two dimension array containing the representation of values from an address profile.
    """


class FillingStrategy(str, Enum):
    """
    Specified whether a filled field was done so by using the html autocomplete attribute or autofill heuristics.
    """

    autocompleteAttribute = "autocompleteAttribute"
    autofillInferred = "autofillInferred"


class FilledField(BaseModel):
    htmlType: str
    """
    The type of the field, e.g text, password etc.
    """
    id: str
    """
    the html id
    """
    name: str
    """
    the html name
    """
    value: str
    """
    the field value
    """
    autofillType: str
    """
    The actual field type, e.g FAMILY_NAME
    """
    fillingStrategy: "FillingStrategy"
    """
    The filling strategy
    """
    frameId: page.FrameId
    """
    The frame the field belongs to
    """
    fieldId: dom.BackendNodeId
    """
    The form field's DOM node
    """
