# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from pydantic import BaseModel, PrivateAttr


class disable(BaseModel):
    """
    Disables inspector domain notifications.
    """

    __domain__: str = PrivateAttr("Inspector")


class enable(BaseModel):
    """
    Enables inspector domain notifications.
    """

    __domain__: str = PrivateAttr("Inspector")
