# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.memory.types import *


class getDOMCounters(BaseModel):
    __domain__: str = PrivateAttr("Memory")


class prepareForLeakDetection(BaseModel):
    __domain__: str = PrivateAttr("Memory")


class forciblyPurgeJavaScriptMemory(BaseModel):
    """
    Simulate OomIntervention by purging V8 memory.
    """

    __domain__: str = PrivateAttr("Memory")


class setPressureNotificationsSuppressed(BaseModel):
    """
    Enable/disable suppressing memory pressure notifications in all processes.
    """

    __domain__: str = PrivateAttr("Memory")
    suppressed: bool
    """
    If true, memory pressure notifications will be suppressed.
    """


class simulatePressureNotification(BaseModel):
    """
    Simulate a memory pressure notification in all processes.
    """

    __domain__: str = PrivateAttr("Memory")
    level: "PressureLevel"
    """
    Memory pressure level of the notification.
    """


class startSampling(BaseModel):
    """
    Start collecting native memory profile.
    """

    __domain__: str = PrivateAttr("Memory")
    samplingInterval: Optional[Union[float, int]]
    """
    Average number of bytes between samples.
    """
    suppressRandomness: Optional[bool]
    """
    Do not randomize intervals between samples.
    """


class stopSampling(BaseModel):
    """
    Stop collecting native memory profile.
    """

    __domain__: str = PrivateAttr("Memory")


class getAllTimeSamplingProfile(BaseModel):
    """
        Retrieve native memory allocations profile
    collected since renderer process startup.
    """

    __domain__: str = PrivateAttr("Memory")


class getBrowserSamplingProfile(BaseModel):
    """
        Retrieve native memory allocations profile
    collected since browser process startup.
    """

    __domain__: str = PrivateAttr("Memory")


class getSamplingProfile(BaseModel):
    """
        Retrieve native memory allocations profile collected since last
    `startSampling` call.
    """

    __domain__: str = PrivateAttr("Memory")
