# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import Union

from pydantic import BaseModel, PrivateAttr


class bind(BaseModel):
    """
    Request browser port binding.
    """

    __domain__: str = PrivateAttr("Tethering")
    port: Union[float, int]
    """
    Port number to bind.
    """


class unbind(BaseModel):
    """
    Request browser port unbinding.
    """

    __domain__: str = PrivateAttr("Tethering")
    port: Union[float, int]
    """
    Port number to unbind.
    """
