# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from pydantic import BaseModel, PrivateAttr


class setInstrumentationBreakpoint(BaseModel):
    """
    Sets breakpoint on particular native event.
    """

    __domain__: str = PrivateAttr("EventBreakpoints")
    eventName: str
    """
    Instrumentation name to stop on.
    """


class removeInstrumentationBreakpoint(BaseModel):
    """
    Removes breakpoint on particular native event.
    """

    __domain__: str = PrivateAttr("EventBreakpoints")
    eventName: str
    """
    Instrumentation name to stop on.
    """


class disable(BaseModel):
    """
    Removes all breakpoints
    """

    __domain__: str = PrivateAttr("EventBreakpoints")
