# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from pydantic import BaseModel, PrivateAttr


class getInfo(BaseModel):
    """
    Returns information about the system.
    """

    __domain__: str = PrivateAttr("SystemInfo")


class getFeatureState(BaseModel):
    """
    Returns information about the feature state.
    """

    __domain__: str = PrivateAttr("SystemInfo")
    featureState: str


class getProcessInfo(BaseModel):
    """
    Returns information about all running processes.
    """

    __domain__: str = PrivateAttr("SystemInfo")
