# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.domains.animation.types import *


class animationCanceled(BaseModel):
    """
    Event for when an animation has been cancelled.
    """

    __domain__: str = PrivateAttr("Animation")
    id: str
    """
    Id of the animation that was cancelled.
    """


class animationCreated(BaseModel):
    """
    Event for each animation that has been created.
    """

    __domain__: str = PrivateAttr("Animation")
    id: str
    """
    Id of the animation that was created.
    """


class animationStarted(BaseModel):
    """
    Event for animation that has been started.
    """

    __domain__: str = PrivateAttr("Animation")
    animation: "Animation"
    """
    Animation that was started.
    """


class animationUpdated(BaseModel):
    """
    Event for animation that has been updated.
    """

    __domain__: str = PrivateAttr("Animation")
    animation: "Animation"
    """
    Animation that was updated.
    """
