# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from pydantic import BaseModel, PrivateAttr


class enable(BaseModel):
    __domain__: str = PrivateAttr("Preload")


class disable(BaseModel):
    __domain__: str = PrivateAttr("Preload")
