# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.media.types import *


class playerPropertiesChanged(BaseModel):
    """
        This can be called multiple times, and can be used to set / override /
    remove player properties. A null propValue indicates removal.
    """

    __domain__: str = PrivateAttr("Media")
    playerId: "PlayerId"
    properties: list


class playerEventsAdded(BaseModel):
    """
        Send events as a list, allowing them to be batched on the browser for less
    congestion. If batched, events must ALWAYS be in chronological order.
    """

    __domain__: str = PrivateAttr("Media")
    playerId: "PlayerId"
    events: list


class playerMessagesLogged(BaseModel):
    """
    Send a list of any messages that need to be delivered.
    """

    __domain__: str = PrivateAttr("Media")
    playerId: "PlayerId"
    messages: list


class playerErrorsRaised(BaseModel):
    """
    Send a list of any errors that need to be delivered.
    """

    __domain__: str = PrivateAttr("Media")
    playerId: "PlayerId"
    errors: list


class playersCreated(BaseModel):
    """
        Called whenever a player is created, or when a new agent joins and receives
    a list of active players. If an agent is restored, it will receive the full
    list of player ids and all events again.
    """

    __domain__: str = PrivateAttr("Media")
    players: list
