# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.backgroundservice.types import *


class startObserving(BaseModel):
    """
    Enables event updates for the service.
    """

    __domain__: str = PrivateAttr("BackgroundService")
    service: "ServiceName"


class stopObserving(BaseModel):
    """
    Disables event updates for the service.
    """

    __domain__: str = PrivateAttr("BackgroundService")
    service: "ServiceName"


class setRecording(BaseModel):
    """
    Set the recording state for the service.
    """

    __domain__: str = PrivateAttr("BackgroundService")
    shouldRecord: bool
    service: "ServiceName"


class clearEvents(BaseModel):
    """
    Clears all stored data for the service.
    """

    __domain__: str = PrivateAttr("BackgroundService")
    service: "ServiceName"
