# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.backgroundservice.types import *


class recordingStateChanged(BaseModel):
    """
    Called when the recording state for the service has been updated.
    """

    __domain__: str = PrivateAttr("BackgroundService")
    isRecording: bool
    service: "ServiceName"


class backgroundServiceEventReceived(BaseModel):
    """
        Called with all existing backgroundServiceEvents when enabled, and all new
    events afterwards if enabled and recording.
    """

    __domain__: str = PrivateAttr("BackgroundService")
    backgroundServiceEvent: "BackgroundServiceEvent"
