# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.audits.types import *


class issueAdded(BaseModel):
    __domain__: str = PrivateAttr("Audits")
    issue: "InspectorIssue"
