# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import Optional

from pydantic import BaseModel


class Sink(BaseModel):
    name: str
    id: str
    session: Optional[str]
    """
    Text describing the current session. Present only if there is an active
session on the sink.
    """
