# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi import dom
from cidipi.layertree.types import *


class layerPainted(BaseModel):
    __domain__: str = PrivateAttr("LayerTree")
    layerId: "LayerId"
    """
    The id of the painted layer.
    """
    clip: dom.Rect
    """
    Clip rectangle.
    """


class layerTreeDidChange(BaseModel):
    __domain__: str = PrivateAttr("LayerTree")
    layers: Optional[list]
    """
    Layer tree, absent if not in the compositing mode.
    """
