# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.domsnapshot.types import *


class disable(BaseModel):
    """
    Disables DOM snapshot agent for the given page.
    """

    __domain__: str = PrivateAttr("DOMSnapshot")


class enable(BaseModel):
    """
    Enables DOM snapshot agent for the given page.
    """

    __domain__: str = PrivateAttr("DOMSnapshot")


class getSnapshot(BaseModel):
    """
        Returns a document snapshot, including the full DOM tree of the root node (including iframes,
    template contents, and imported documents) in a flattened array, as well as layout and
    white-listed computed style information for the nodes. Shadow DOM in the returned DOM tree is
    flattened.
    """

    __domain__: str = PrivateAttr("DOMSnapshot")
    computedStyleWhitelist: list
    """
    Whitelist of computed styles to return.
    """
    includeEventListeners: Optional[bool]
    """
    Whether or not to retrieve details of DOM listeners (default false).
    """
    includePaintOrder: Optional[bool]
    """
    Whether to determine and include the paint order index of LayoutTreeNodes (default false).
    """
    includeUserAgentShadowTree: Optional[bool]
    """
    Whether to include UA shadow tree in the snapshot (default false).
    """


class captureSnapshot(BaseModel):
    """
        Returns a document snapshot, including the full DOM tree of the root node (including iframes,
    template contents, and imported documents) in a flattened array, as well as layout and
    white-listed computed style information for the nodes. Shadow DOM in the returned DOM tree is
    flattened.
    """

    __domain__: str = PrivateAttr("DOMSnapshot")
    computedStyles: list
    """
    Whitelist of computed styles to return.
    """
    includePaintOrder: Optional[bool]
    """
    Whether to include layout object paint orders into the snapshot.
    """
    includeDOMRects: Optional[bool]
    """
    Whether to include DOM rectangles (offsetRects, clientRects, scrollRects) into the snapshot
    """
    includeBlendedBackgroundColors: Optional[bool]
    """
    Whether to include blended background colors in the snapshot (default: false).
Blended background color is achieved by blending background colors of all elements
that overlap with the current element.
    """
    includeTextColorOpacities: Optional[bool]
    """
    Whether to include text color opacity in the snapshot (default: false).
An element might have the opacity property set that affects the text color of the element.
The final text color opacity is computed based on the opacity of all overlapping elements.
    """
