# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from enum import Enum
from typing import Literal, Optional, TypeVar

from pydantic import BaseModel

from cidipi.domains import network

RequestId = TypeVar("RequestId", bound=str)
"""
Unique request identifier.
"""


class RequestStage(str, Enum):
    """
        Stages of the request to handle. Request will intercept before the request is
    sent. Response will intercept after the response is received (but before response
    body is received).
    """

    Request = "Request"
    Response = "Response"


class RequestPattern(BaseModel):
    urlPattern: Optional[str]
    """
    Wildcards (`'*'` -> zero or more, `'?'` -> exactly one) are allowed. Escape character is
backslash. Omitting is equivalent to `"*"`.
    """
    resourceType: Optional[network.ResourceType]
    """
    If set, only requests for matching resource types will be intercepted.
    """
    requestStage: Optional["RequestStage"]
    """
    Stage at which to begin intercepting requests. Default is Request.
    """


class HeaderEntry(BaseModel):
    """
    Response HTTP header entry
    """

    name: str
    value: str


class AuthChallenge(BaseModel):
    """
    Authorization challenge for HTTP status code 401 or 407.
    """

    source: Optional[Literal["Server", "Proxy"]]
    """
    Source of the authentication challenge.
    """
    origin: str
    """
    Origin of the challenger.
    """
    scheme: str
    """
    The authentication scheme used, such as basic or digest
    """
    realm: str
    """
    The realm of the challenge. May be empty.
    """


class AuthChallengeResponse(BaseModel):
    """
    Response to an AuthChallenge.
    """

    response: Literal["Default", "CancelAuth", "ProvideCredentials"]
    """
    The decision on what to do in response to the authorization challenge.  Default means
deferring to the default behavior of the net stack, which will likely either the Cancel
authentication or display a popup dialog box.
    """
    username: Optional[str]
    """
    The username to provide, possibly empty. Should only be set if response is
ProvideCredentials.
    """
    password: Optional[str]
    """
    The password to provide, possibly empty. Should only be set if response is
ProvideCredentials.
    """
