# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.fedcm.types import *


class enable(BaseModel):
    __domain__: str = PrivateAttr("FedCm")
    disableRejectionDelay: Optional[bool]
    """
    Allows callers to disable the promise rejection delay that would
normally happen, if this is unimportant to what's being tested.
(step 4 of https://fedidcg.github.io/FedCM/#browser-api-rp-sign-in)
    """


class disable(BaseModel):
    __domain__: str = PrivateAttr("FedCm")


class selectAccount(BaseModel):
    __domain__: str = PrivateAttr("FedCm")
    dialogId: str
    accountIndex: Union[float, int]


class clickDialogButton(BaseModel):
    __domain__: str = PrivateAttr("FedCm")
    dialogId: str
    dialogButton: "DialogButton"


class openUrl(BaseModel):
    __domain__: str = PrivateAttr("FedCm")
    dialogId: str
    accountIndex: Union[float, int]
    accountUrlType: "AccountUrlType"


class dismissDialog(BaseModel):
    __domain__: str = PrivateAttr("FedCm")
    dialogId: str
    triggerCooldown: Optional[bool]


class resetCooldown(BaseModel):
    """
        Resets the cooldown time, if any, to allow the next FedCM call to show
    a dialog even if one was recently dismissed by the user.
    """

    __domain__: str = PrivateAttr("FedCm")
