# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from enum import Enum
from typing import Optional

from pydantic import BaseModel


class LoginState(str, Enum):
    """
        Whether this is a sign-up or sign-in action for this account, i.e.
    whether this account has ever been used to sign in to this RP before.
    """

    SignIn = "SignIn"
    SignUp = "SignUp"


class DialogType(str, Enum):
    """
    The types of FedCM dialogs.
    """

    AccountChooser = "AccountChooser"
    AutoReauthn = "AutoReauthn"
    ConfirmIdpLogin = "ConfirmIdpLogin"
    Error = "Error"


class DialogButton(str, Enum):
    """
    The buttons on the FedCM dialog.
    """

    ConfirmIdpLoginContinue = "ConfirmIdpLoginContinue"
    ErrorGotIt = "ErrorGotIt"
    ErrorMoreDetails = "ErrorMoreDetails"


class AccountUrlType(str, Enum):
    """
    The URLs that each account has
    """

    TermsOfService = "TermsOfService"
    PrivacyPolicy = "PrivacyPolicy"


class Account(BaseModel):
    """
    Corresponds to IdentityRequestAccount
    """

    accountId: str
    email: str
    name: str
    givenName: str
    pictureUrl: str
    idpConfigUrl: str
    idpLoginUrl: str
    loginState: "LoginState"
    termsOfServiceUrl: Optional[str]
    """
    These two are only set if the loginState is signUp
    """
    privacyPolicyUrl: Optional[str]
