# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.runtime.types import *


class awaitPromise(BaseModel):
    """
    Add handler to promise with given promise object id.
    """

    __domain__: str = PrivateAttr("Runtime")
    promiseObjectId: "RemoteObjectId"
    """
    Identifier of the promise.
    """
    returnByValue: Optional[bool]
    """
    Whether the result is expected to be a JSON object that should be sent by value.
    """
    generatePreview: Optional[bool]
    """
    Whether preview should be generated for the result.
    """


class callFunctionOn(BaseModel):
    """
        Calls function with given declaration on the given object. Object group of the result is
    inherited from the target object.
    """

    __domain__: str = PrivateAttr("Runtime")
    functionDeclaration: str
    """
    Declaration of the function to call.
    """
    objectId: Optional["RemoteObjectId"]
    """
    Identifier of the object to call function on. Either objectId or executionContextId should
be specified.
    """
    arguments: Optional[list]
    """
    Call arguments. All call arguments must belong to the same JavaScript world as the target
object.
    """
    silent: Optional[bool]
    """
    In silent mode exceptions thrown during evaluation are not reported and do not pause
execution. Overrides `setPauseOnException` state.
    """
    returnByValue: Optional[bool]
    """
    Whether the result is expected to be a JSON object which should be sent by value.
Can be overriden by `serializationOptions`.
    """
    generatePreview: Optional[bool]
    """
    Whether preview should be generated for the result.
    """
    userGesture: Optional[bool]
    """
    Whether execution should be treated as initiated by user in the UI.
    """
    awaitPromise: Optional[bool]
    """
    Whether execution should `await` for resulting value and return once awaited promise is
resolved.
    """
    executionContextId: Optional["ExecutionContextId"]
    """
    Specifies execution context which global object will be used to call function on. Either
executionContextId or objectId should be specified.
    """
    objectGroup: Optional[str]
    """
    Symbolic group name that can be used to release multiple objects. If objectGroup is not
specified and objectId is, objectGroup will be inherited from object.
    """
    throwOnSideEffect: Optional[bool]
    """
    Whether to throw an exception if side effect cannot be ruled out during evaluation.
    """
    uniqueContextId: Optional[str]
    """
    An alternative way to specify the execution context to call function on.
Compared to contextId that may be reused across processes, this is guaranteed to be
system-unique, so it can be used to prevent accidental function call
in context different than intended (e.g. as a result of navigation across process
boundaries).
This is mutually exclusive with `executionContextId`.
    """
    serializationOptions: Optional["SerializationOptions"]
    """
    Specifies the result serialization. If provided, overrides
`generatePreview` and `returnByValue`.
    """


class compileScript(BaseModel):
    """
    Compiles expression.
    """

    __domain__: str = PrivateAttr("Runtime")
    expression: str
    """
    Expression to compile.
    """
    sourceURL: str
    """
    Source url to be set for the script.
    """
    persistScript: bool
    """
    Specifies whether the compiled script should be persisted.
    """
    executionContextId: Optional["ExecutionContextId"]
    """
    Specifies in which execution context to perform script run. If the parameter is omitted the
evaluation will be performed in the context of the inspected page.
    """


class disable(BaseModel):
    """
    Disables reporting of execution contexts creation.
    """

    __domain__: str = PrivateAttr("Runtime")


class discardConsoleEntries(BaseModel):
    """
    Discards collected exceptions and console API calls.
    """

    __domain__: str = PrivateAttr("Runtime")


class enable(BaseModel):
    """
        Enables reporting of execution contexts creation by means of `executionContextCreated` event.
    When the reporting gets enabled the event will be sent immediately for each existing execution
    context.
    """

    __domain__: str = PrivateAttr("Runtime")


class evaluate(BaseModel):
    """
    Evaluates expression on global object.
    """

    __domain__: str = PrivateAttr("Runtime")
    expression: str
    """
    Expression to evaluate.
    """
    objectGroup: Optional[str]
    """
    Symbolic group name that can be used to release multiple objects.
    """
    includeCommandLineAPI: Optional[bool]
    """
    Determines whether Command Line API should be available during the evaluation.
    """
    silent: Optional[bool]
    """
    In silent mode exceptions thrown during evaluation are not reported and do not pause
execution. Overrides `setPauseOnException` state.
    """
    contextId: Optional["ExecutionContextId"]
    """
    Specifies in which execution context to perform evaluation. If the parameter is omitted the
evaluation will be performed in the context of the inspected page.
This is mutually exclusive with `uniqueContextId`, which offers an
alternative way to identify the execution context that is more reliable
in a multi-process environment.
    """
    returnByValue: Optional[bool]
    """
    Whether the result is expected to be a JSON object that should be sent by value.
    """
    generatePreview: Optional[bool]
    """
    Whether preview should be generated for the result.
    """
    userGesture: Optional[bool]
    """
    Whether execution should be treated as initiated by user in the UI.
    """
    awaitPromise: Optional[bool]
    """
    Whether execution should `await` for resulting value and return once awaited promise is
resolved.
    """
    throwOnSideEffect: Optional[bool]
    """
    Whether to throw an exception if side effect cannot be ruled out during evaluation.
This implies `disableBreaks` below.
    """
    timeout: Optional["TimeDelta"]
    """
    Terminate execution after timing out (number of milliseconds).
    """
    disableBreaks: Optional[bool]
    """
    Disable breakpoints during execution.
    """
    replMode: Optional[bool]
    """
    Setting this flag to true enables `let` re-declaration and top-level `await`.
Note that `let` variables can only be re-declared if they originate from
`replMode` themselves.
    """
    allowUnsafeEvalBlockedByCSP: Optional[bool]
    """
    The Content Security Policy (CSP) for the target might block 'unsafe-eval'
which includes eval(), Function(), setTimeout() and setInterval()
when called with non-callable arguments. This flag bypasses CSP for this
evaluation and allows unsafe-eval. Defaults to true.
    """
    uniqueContextId: Optional[str]
    """
    An alternative way to specify the execution context to evaluate in.
Compared to contextId that may be reused across processes, this is guaranteed to be
system-unique, so it can be used to prevent accidental evaluation of the expression
in context different than intended (e.g. as a result of navigation across process
boundaries).
This is mutually exclusive with `contextId`.
    """
    serializationOptions: Optional["SerializationOptions"]
    """
    Specifies the result serialization. If provided, overrides
`generatePreview` and `returnByValue`.
    """


class getIsolateId(BaseModel):
    """
    Returns the isolate id.
    """

    __domain__: str = PrivateAttr("Runtime")


class getHeapUsage(BaseModel):
    """
        Returns the JavaScript heap usage.
    It is the total usage of the corresponding isolate not scoped to a particular Runtime.
    """

    __domain__: str = PrivateAttr("Runtime")


class getProperties(BaseModel):
    """
        Returns properties of a given object. Object group of the result is inherited from the target
    object.
    """

    __domain__: str = PrivateAttr("Runtime")
    objectId: "RemoteObjectId"
    """
    Identifier of the object to return properties for.
    """
    ownProperties: Optional[bool]
    """
    If true, returns properties belonging only to the element itself, not to its prototype
chain.
    """
    accessorPropertiesOnly: Optional[bool]
    """
    If true, returns accessor properties (with getter/setter) only; internal properties are not
returned either.
    """
    generatePreview: Optional[bool]
    """
    Whether preview should be generated for the results.
    """
    nonIndexedPropertiesOnly: Optional[bool]
    """
    If true, returns non-indexed properties only.
    """


class globalLexicalScopeNames(BaseModel):
    """
    Returns all let, const and class variables from global scope.
    """

    __domain__: str = PrivateAttr("Runtime")
    executionContextId: Optional["ExecutionContextId"]
    """
    Specifies in which execution context to lookup global scope variables.
    """


class queryObjects(BaseModel):
    __domain__: str = PrivateAttr("Runtime")
    prototypeObjectId: "RemoteObjectId"
    """
    Identifier of the prototype to return objects for.
    """
    objectGroup: Optional[str]
    """
    Symbolic group name that can be used to release the results.
    """


class releaseObject(BaseModel):
    """
    Releases remote object with given id.
    """

    __domain__: str = PrivateAttr("Runtime")
    objectId: "RemoteObjectId"
    """
    Identifier of the object to release.
    """


class releaseObjectGroup(BaseModel):
    """
    Releases all remote objects that belong to a given group.
    """

    __domain__: str = PrivateAttr("Runtime")
    objectGroup: str
    """
    Symbolic object group name.
    """


class runIfWaitingForDebugger(BaseModel):
    """
    Tells inspected instance to run if it was waiting for debugger to attach.
    """

    __domain__: str = PrivateAttr("Runtime")


class runScript(BaseModel):
    """
    Runs script with given id in a given context.
    """

    __domain__: str = PrivateAttr("Runtime")
    scriptId: "ScriptId"
    """
    Id of the script to run.
    """
    executionContextId: Optional["ExecutionContextId"]
    """
    Specifies in which execution context to perform script run. If the parameter is omitted the
evaluation will be performed in the context of the inspected page.
    """
    objectGroup: Optional[str]
    """
    Symbolic group name that can be used to release multiple objects.
    """
    silent: Optional[bool]
    """
    In silent mode exceptions thrown during evaluation are not reported and do not pause
execution. Overrides `setPauseOnException` state.
    """
    includeCommandLineAPI: Optional[bool]
    """
    Determines whether Command Line API should be available during the evaluation.
    """
    returnByValue: Optional[bool]
    """
    Whether the result is expected to be a JSON object which should be sent by value.
    """
    generatePreview: Optional[bool]
    """
    Whether preview should be generated for the result.
    """
    awaitPromise: Optional[bool]
    """
    Whether execution should `await` for resulting value and return once awaited promise is
resolved.
    """


class setAsyncCallStackDepth(BaseModel):
    """
    Enables or disables async call stacks tracking.
    """

    __domain__: str = PrivateAttr("Runtime")
    maxDepth: Union[float, int]
    """
    Maximum depth of async call stacks. Setting to `0` will effectively disable collecting async
call stacks (default).
    """


class setCustomObjectFormatterEnabled(BaseModel):
    __domain__: str = PrivateAttr("Runtime")
    enabled: bool


class setMaxCallStackSizeToCapture(BaseModel):
    __domain__: str = PrivateAttr("Runtime")
    size: Union[float, int]


class terminateExecution(BaseModel):
    """
        Terminate current or next JavaScript execution.
    Will cancel the termination when the outer-most script execution ends.
    """

    __domain__: str = PrivateAttr("Runtime")


class addBinding(BaseModel):
    """
        If executionContextId is empty, adds binding with the given name on the
    global objects of all inspected contexts, including those created later,
    bindings survive reloads.
    Binding function takes exactly one argument, this argument should be string,
    in case of any other input, function throws an exception.
    Each binding function call produces Runtime.bindingCalled notification.
    """

    __domain__: str = PrivateAttr("Runtime")
    name: str
    executionContextId: Optional["ExecutionContextId"]
    """
    If specified, the binding would only be exposed to the specified
execution context. If omitted and `executionContextName` is not set,
the binding is exposed to all execution contexts of the target.
This parameter is mutually exclusive with `executionContextName`.
Deprecated in favor of `executionContextName` due to an unclear use case
and bugs in implementation (crbug.com/1169639). `executionContextId` will be
removed in the future.
    """
    executionContextName: Optional[str]
    """
    If specified, the binding is exposed to the executionContext with
matching name, even for contexts created after the binding is added.
See also `ExecutionContext.name` and `worldName` parameter to
`Page.addScriptToEvaluateOnNewDocument`.
This parameter is mutually exclusive with `executionContextId`.
    """


class removeBinding(BaseModel):
    """
        This method does not remove binding function from global object but
    unsubscribes current runtime agent from Runtime.bindingCalled notifications.
    """

    __domain__: str = PrivateAttr("Runtime")
    name: str


class getExceptionDetails(BaseModel):
    """
        This method tries to lookup and populate exception details for a
    JavaScript Error object.
    Note that the stackTrace portion of the resulting exceptionDetails will
    only be populated if the Runtime domain was enabled at the time when the
    Error was thrown.
    """

    __domain__: str = PrivateAttr("Runtime")
    errorObjectId: "RemoteObjectId"
    """
    The error object for which to resolve the exception details.
    """
