# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.domains import dom, page, runtime
from cidipi.domains.accessibility.types import *


class disable(BaseModel):
    """
    Disables the accessibility domain.
    """

    __domain__: str = PrivateAttr("Accessibility")


class enable(BaseModel):
    """
        Enables the accessibility domain which causes `AXNodeId`s to remain consistent between method calls.
    This turns on accessibility for the page, which can impact performance until accessibility is disabled.
    """

    __domain__: str = PrivateAttr("Accessibility")


class getPartialAXTree(BaseModel):
    """
    Fetches the accessibility node and partial accessibility tree for this DOM node, if it exists.
    """

    __domain__: str = PrivateAttr("Accessibility")
    nodeId: Optional[dom.NodeId]
    """
    Identifier of the node to get the partial accessibility tree for.
    """
    backendNodeId: Optional[dom.BackendNodeId]
    """
    Identifier of the backend node to get the partial accessibility tree for.
    """
    objectId: Optional[runtime.RemoteObjectId]
    """
    JavaScript object id of the node wrapper to get the partial accessibility tree for.
    """
    fetchRelatives: Optional[bool]
    """
    Whether to fetch this node's ancestors, siblings and children. Defaults to true.
    """


class getFullAXTree(BaseModel):
    """
    Fetches the entire accessibility tree for the root Document
    """

    __domain__: str = PrivateAttr("Accessibility")
    depth: Optional[Union[float, int]]
    """
    The maximum depth at which descendants of the root node should be retrieved.
If omitted, the full tree is returned.
    """
    frameId: Optional[page.FrameId]
    """
    The frame for whose document the AX tree should be retrieved.
If omitted, the root frame is used.
    """


class getRootAXNode(BaseModel):
    """
        Fetches the root node.
    Requires `enable()` to have been called previously.
    """

    __domain__: str = PrivateAttr("Accessibility")
    frameId: Optional[page.FrameId]
    """
    The frame in whose document the node resides.
If omitted, the root frame is used.
    """


class getAXNodeAndAncestors(BaseModel):
    """
        Fetches a node and all ancestors up to and including the root.
    Requires `enable()` to have been called previously.
    """

    __domain__: str = PrivateAttr("Accessibility")
    nodeId: Optional[dom.NodeId]
    """
    Identifier of the node to get.
    """
    backendNodeId: Optional[dom.BackendNodeId]
    """
    Identifier of the backend node to get.
    """
    objectId: Optional[runtime.RemoteObjectId]
    """
    JavaScript object id of the node wrapper to get.
    """


class getChildAXNodes(BaseModel):
    """
        Fetches a particular accessibility node by AXNodeId.
    Requires `enable()` to have been called previously.
    """

    __domain__: str = PrivateAttr("Accessibility")
    id: "AXNodeId"
    frameId: Optional[page.FrameId]
    """
    The frame in whose document the node resides.
If omitted, the root frame is used.
    """


class queryAXTree(BaseModel):
    """
        Query a DOM node's accessibility subtree for accessible name and role.
    This command computes the name and role for all nodes in the subtree, including those that are
    ignored for accessibility, and returns those that match the specified name and role. If no DOM
    node is specified, or the DOM node does not exist, the command returns an error. If neither
    `accessibleName` or `role` is specified, it returns all the accessibility nodes in the subtree.
    """

    __domain__: str = PrivateAttr("Accessibility")
    nodeId: Optional[dom.NodeId]
    """
    Identifier of the node for the root to query.
    """
    backendNodeId: Optional[dom.BackendNodeId]
    """
    Identifier of the backend node for the root to query.
    """
    objectId: Optional[runtime.RemoteObjectId]
    """
    JavaScript object id of the node wrapper for the root to query.
    """
    accessibleName: Optional[str]
    """
    Find nodes with this computed name.
    """
    role: Optional[str]
    """
    Find nodes with this computed role.
    """
