# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import TypeVar

StreamHandle = TypeVar("StreamHandle", bound=str)
"""
This is either obtained from another method or specified as `blob:<uuid>` where
`<uuid>` is an UUID of a Blob.
"""
