# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from pydantic import BaseModel, PrivateAttr


class enable(BaseModel):
    """
    Enables the Media domain
    """

    __domain__: str = PrivateAttr("Media")


class disable(BaseModel):
    """
    Disables the Media domain.
    """

    __domain__: str = PrivateAttr("Media")
