# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from pydantic import BaseModel, PrivateAttr


class metrics(BaseModel):
    """
    Current values of the metrics.
    """

    __domain__: str = PrivateAttr("Performance")
    metrics: list
    """
    Current values of the metrics.
    """
    title: str
    """
    Timestamp title.
    """
