# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi import dom, page
from cidipi.autofill.types import *


class trigger(BaseModel):
    """
        Trigger autofill on a form identified by the fieldId.
    If the field and related form cannot be autofilled, returns an error.
    """

    __domain__: str = PrivateAttr("Autofill")
    fieldId: dom.BackendNodeId
    """
    Identifies a field that serves as an anchor for autofill.
    """
    frameId: Optional[page.FrameId]
    """
    Identifies the frame that field belongs to.
    """
    card: "CreditCard"
    """
    Credit card information to fill out the form. Credit card data is not saved.
    """


class setAddresses(BaseModel):
    """
    Set addresses so that developers can verify their forms implementation.
    """

    __domain__: str = PrivateAttr("Autofill")
    addresses: list


class disable(BaseModel):
    """
    Disables autofill domain notifications.
    """

    __domain__: str = PrivateAttr("Autofill")


class enable(BaseModel):
    """
    Enables autofill domain notifications.
    """

    __domain__: str = PrivateAttr("Autofill")
