# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.domains import storage
from cidipi.domains.indexeddb.types import *


class clearObjectStore(BaseModel):
    """
    Clears all entries from an object store.
    """

    __domain__: str = PrivateAttr("IndexedDB")
    securityOrigin: Optional[str]
    """
    At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
Security origin.
    """
    storageKey: Optional[str]
    """
    Storage key.
    """
    storageBucket: Optional[storage.StorageBucket]
    """
    Storage bucket. If not specified, it uses the default bucket.
    """
    databaseName: str
    """
    Database name.
    """
    objectStoreName: str
    """
    Object store name.
    """


class deleteDatabase(BaseModel):
    """
    Deletes a database.
    """

    __domain__: str = PrivateAttr("IndexedDB")
    securityOrigin: Optional[str]
    """
    At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
Security origin.
    """
    storageKey: Optional[str]
    """
    Storage key.
    """
    storageBucket: Optional[storage.StorageBucket]
    """
    Storage bucket. If not specified, it uses the default bucket.
    """
    databaseName: str
    """
    Database name.
    """


class deleteObjectStoreEntries(BaseModel):
    """
    Delete a range of entries from an object store
    """

    __domain__: str = PrivateAttr("IndexedDB")
    securityOrigin: Optional[str]
    """
    At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
Security origin.
    """
    storageKey: Optional[str]
    """
    Storage key.
    """
    storageBucket: Optional[storage.StorageBucket]
    """
    Storage bucket. If not specified, it uses the default bucket.
    """
    databaseName: str
    objectStoreName: str
    keyRange: "KeyRange"
    """
    Range of entry keys to delete
    """


class disable(BaseModel):
    """
    Disables events from backend.
    """

    __domain__: str = PrivateAttr("IndexedDB")


class enable(BaseModel):
    """
    Enables events from backend.
    """

    __domain__: str = PrivateAttr("IndexedDB")


class requestData(BaseModel):
    """
    Requests data from object store or index.
    """

    __domain__: str = PrivateAttr("IndexedDB")
    securityOrigin: Optional[str]
    """
    At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
Security origin.
    """
    storageKey: Optional[str]
    """
    Storage key.
    """
    storageBucket: Optional[storage.StorageBucket]
    """
    Storage bucket. If not specified, it uses the default bucket.
    """
    databaseName: str
    """
    Database name.
    """
    objectStoreName: str
    """
    Object store name.
    """
    indexName: str
    """
    Index name, empty string for object store data requests.
    """
    skipCount: Union[float, int]
    """
    Number of records to skip.
    """
    pageSize: Union[float, int]
    """
    Number of records to fetch.
    """
    keyRange: Optional["KeyRange"]
    """
    Key range.
    """


class getMetadata(BaseModel):
    """
    Gets metadata of an object store.
    """

    __domain__: str = PrivateAttr("IndexedDB")
    securityOrigin: Optional[str]
    """
    At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
Security origin.
    """
    storageKey: Optional[str]
    """
    Storage key.
    """
    storageBucket: Optional[storage.StorageBucket]
    """
    Storage bucket. If not specified, it uses the default bucket.
    """
    databaseName: str
    """
    Database name.
    """
    objectStoreName: str
    """
    Object store name.
    """


class requestDatabase(BaseModel):
    """
    Requests database with given name in given frame.
    """

    __domain__: str = PrivateAttr("IndexedDB")
    securityOrigin: Optional[str]
    """
    At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
Security origin.
    """
    storageKey: Optional[str]
    """
    Storage key.
    """
    storageBucket: Optional[storage.StorageBucket]
    """
    Storage bucket. If not specified, it uses the default bucket.
    """
    databaseName: str
    """
    Database name.
    """


class requestDatabaseNames(BaseModel):
    """
    Requests database names for given security origin.
    """

    __domain__: str = PrivateAttr("IndexedDB")
    securityOrigin: Optional[str]
    """
    At least and at most one of securityOrigin, storageKey, or storageBucket must be specified.
Security origin.
    """
    storageKey: Optional[str]
    """
    Storage key.
    """
    storageBucket: Optional[storage.StorageBucket]
    """
    Storage bucket. If not specified, it uses the default bucket.
    """
