# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.input.types import *


class dragIntercepted(BaseModel):
    """
        Emitted only when `Input.setInterceptDrags` is enabled. Use this data with `Input.dispatchDragEvent` to
    restore normal drag and drop behavior.
    """

    __domain__: str = PrivateAttr("Input")
    data: "DragData"
