# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.database.types import *


class addDatabase(BaseModel):
    __domain__: str = PrivateAttr("Database")
    database: "Database"
