# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import TypeVar, Union

from pydantic import BaseModel

DatabaseId = TypeVar("DatabaseId", bound=str)
"""
Unique identifier of Database object.
"""


class Database(BaseModel):
    """
    Database object.
    """

    id: "DatabaseId"
    """
    Database ID.
    """
    domain: str
    """
    Database domain.
    """
    name: str
    """
    Database name.
    """
    version: str
    """
    Database version.
    """


class Error(BaseModel):
    """
    Database error.
    """

    message: str
    """
    Error message.
    """
    code: Union[float, int]
    """
    Error code.
    """
