# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from pydantic import BaseModel


class FileHandlerAccept(BaseModel):
    """
        The following types are the replica of
    https://crsrc.org/c/chrome/browser/web_applications/proto/web_app_os_integration_state.proto;drc=9910d3be894c8f142c977ba1023f30a656bc13fc;l=67
    """

    mediaType: str
    """
    New name of the mimetype according to
https://www.iana.org/assignments/media-types/media-types.xhtml
    """
    fileExtensions: list


class FileHandler(BaseModel):
    action: str
    accepts: list
    displayName: str
