# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.accessibility.types import *


class loadComplete(BaseModel):
    """
        The loadComplete event mirrors the load complete event sent by the browser to assistive
    technology when the web page has finished loading.
    """

    __domain__: str = PrivateAttr("Accessibility")
    root: "AXNode"
    """
    New document root node.
    """


class nodesUpdated(BaseModel):
    """
    The nodesUpdated event is sent every time a previously requested node has changed the in tree.
    """

    __domain__: str = PrivateAttr("Accessibility")
    nodes: list
    """
    Updated node data.
    """
