# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from pydantic import BaseModel, PrivateAttr


class enable(BaseModel):
    """
        Previously buffered events would be reported before method returns.
    See also: timelineEventAdded
    """

    __domain__: str = PrivateAttr("PerformanceTimeline")
    eventTypes: list
    """
    The types of event to report, as specified in
https://w3c.github.io/performance-timeline/#dom-performanceentry-entrytype
The specified filter overrides any previous filters, passing empty
filter disables recording.
Note that not all types exposed to the web platform are currently supported.
    """
