# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.domains.performancetimeline.types import *


class timelineEventAdded(BaseModel):
    """
    Sent when a performance timeline event is added. See reportPerformanceTimeline method.
    """

    __domain__: str = PrivateAttr("PerformanceTimeline")
    event: "TimelineEvent"
