# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from pydantic import BaseModel, PrivateAttr


class virtualTimeBudgetExpired(BaseModel):
    """
    Notification sent after the virtual time budget for the current VirtualTimePolicy has run out.
    """

    __domain__: str = PrivateAttr("Emulation")
