# AUTO-GENERATED By cidipi/tools/generator.py. DO NOT EDIT.

from typing import *

from pydantic import BaseModel, PrivateAttr

from cidipi.domstorage.types import *


class domStorageItemAdded(BaseModel):
    __domain__: str = PrivateAttr("DOMStorage")
    storageId: "StorageId"
    key: str
    newValue: str


class domStorageItemRemoved(BaseModel):
    __domain__: str = PrivateAttr("DOMStorage")
    storageId: "StorageId"
    key: str


class domStorageItemUpdated(BaseModel):
    __domain__: str = PrivateAttr("DOMStorage")
    storageId: "StorageId"
    key: str
    oldValue: str
    newValue: str


class domStorageItemsCleared(BaseModel):
    __domain__: str = PrivateAttr("DOMStorage")
    storageId: "StorageId"
